spring:
  application:
    name: currencyConverter
server:
  port: 9083

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eurekaserver:8761/eureka
  instance:
    hostname: localhost