#Deployment file

apiVersion: apps/v1
kind: Deployment
metadata:
  name: managecurrencyconversion-deployment
  labels:
    app: managecurrencyconversion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: managecurrencyconversion
  template:
    metadata:
      labels:
        app: managecurrencyconversion
    spec:
      containers:
        - name: managecurrencyconversion
          imagePullPolicy: Never
          image: managecurrencyconversion
          ports:
          - containerPort: 9082
          env:
            - name: _JAVA_OPTIONS
              value: -Deureka.client.serviceUrl.defaultZone=http://eurekaserver:8761/eureka/
            - name: EUREKA_CLIENT_REGISTERWITHEUREKA
              value: "true"
            - name: EUREKA_CLIENT_FETCHREGISTRY
              value: "true"
---
#service file

apiVersion: v1
kind: Service
metadata:
  name: managecurrencyconversion
spec:
  type: NodePort
  ports:
    - port: 9082 #service port
      targetPort: 9082 #container port
      nodePort: 31766 # listening port of the node for external service
  selector:
    app: managecurrencyconversion