spring:
  application:
    name: manageCurrencyConversion
  h2:
    console:
      enabled: true
      path: /h2
      
  datasource:
    driverClassName: org.h2.Driver 
    url: jdbc:h2:file:~/test
    username: sa
    password: 
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost